x-server-template: &server-template
  build: .
  environment:
    - PAYMENT_WORKERS_COUNT=50
    - PAYMENT_WORKERS_EVENTS_BUFFER_SIZE=10000
    - SERVER_PORT=8080
    - CACHE_HOST=cache
    - CACHE_PORT=6379
    - CACHE_PASSWORD=password
    - PAYMENT_DEFAULT_URL=http://payment-processor-default:8080
    - PAYMENT_FALLBACK_URL=http://payment-processor-fallback:8080
  depends_on:
    cache:
      condition: service_healthy
  restart: unless-stopped
  networks:
    - backend
    - payment-processor

services:
  load-balancer:
    image: nginx:alpine
    volumes:
      - ./project/load-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:80"
    networks:
      - backend
    depends_on:
      - server-cache-1
      - server-cache-2
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 30M

  server-cache-1:
    <<: *server-template
    container_name: server-cache-1
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 60M
  server-cache-2:
    <<: *server-template
    container_name: server-cache-2
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 60M

  cache:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=password
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "password", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    container_name: server-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - cache-data:/data
    networks:
      - backend

volumes:
  cache-data:

networks:
  backend:
    driver: bridge
  # payment-processor must be up before starting backend network
  payment-processor:
    external: true
